#!/bin/bash

Apt-get update
apt-get -y install nginx

#герерация ключа
openssl genrsa -out /etc/ssl/certs/root-ca.key 2048

#генерация корневого сертификата
openssl req -x509 -new -key /etc/ssl/certs/root-ca.key -days 365 -out /etc/ssl/certs/root-ca.crt \
-subj "/C=UA/ST=Kharkov/L=Kharkov/O=Student/CN=noob.studio"

#генерируем сертификат, подписанный нами же
openssl genrsa -out /etc/ssl/certs/selfCA.key 2048

#генерим запрос на сертификат
openssl req -new -newkey rsa:4096 -key /etc/ssl/certs/selfCA.key \
out -/etc/ssl/vm1.crt \
-subj "/C=UA/ST=Kharkov/L=Kharkov/O=Student/CN=vm1"

#подписываем запрос на сертификат
openssl x509 -req -in /etc/ssl/vm1.csr -CA /etc/ssl/certs/root-ca.crt -CA /etc/ssl/certs/root-ca.key -Cacreateseial -out /etc/ssl/vm1.crt -days 100

