#!/bin/bash

cat << 'EOF' > /etc/network/interfaces
root@vm1:/etc/network# cat interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto ens3
iface ens3 inet dhcp

auto ens9
iface ens9 inet dhcp
# address 10.0.0.1
# netmask 255.255.255.0

auto ens9.278
iface ens9.278 inet static
 address 200.0.0.1
 netmask 255.255.255.0
 vlan_raw_device ens9


EOF

service networking restart

